# Generated by Django 4.2.3 on 2023-07-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coursesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSubscription',
        ),
    ]
