# Generated by Django 4.2.3 on 2023-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_school', '0002_course_user_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка к курсу'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media_lesson/', verbose_name='картинка урока'),
        ),
    ]
