# Generated by Django 4.2.3 on 2023-07-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cool_school', '0003_alter_course_preview_alter_lesson_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
