# Generated by Django 4.2.3 on 2023-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool_school', '0012_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ссылка на урок'),
        ),
    ]
